# Laboratorium 4 — NumPy zaawansowane
**Autor:** [Krzysztof Majiczek]

In [1]:
import numpy as np


Ćwiczenie 1: Broadcasting — zastosowania biznesowe (20
min)
Cel
Użyj broadcastingu do obliczeń na danych o różnych kształtach.


Krok 1 - Dane


In [2]:
# Ceny 4 produktów w 3 sklepach
ceny = np.array([[29.99, 31.99, 28.99], # Produkt A
[49.99, 52.99, 47.99], # Produkt B
[14.99, 15.99, 13.99], # Produkt C
[99.99, 104.99, 94.99]]) # Produkt D
sklepy = ['Centrum', 'Galeria', 'Online']
produkty = ['A', 'B', 'C', 'D']
print(f"Kształt macierzy: {ceny.shape}") # (4, 3)

Kształt macierzy: (4, 3)


Zadanie 1a: Stwórz nowy array z cenami podniesionymi o 5% (inflacja).
Wyświetl wynik.

In [3]:
ceny_105 = ceny * 1.05
print(f"Ceny po podwyżce o 5%:\n{ceny_105}")

Ceny po podwyżce o 5%:
[[ 31.4895  33.5895  30.4395]
 [ 52.4895  55.6395  50.3895]
 [ 15.7395  16.7895  14.6895]
 [104.9895 110.2395  99.7395]]


Zadanie 1b: Stwórz array z cenami po rabacie. Każdy sklep daje inny rabat:
Centrum 10%, Galeria 5%, Online 15%.

In [4]:
rabaty = np.array([0.10, 0.05, 0.15])
ceny_po_rabacie = ceny * (1 - rabaty)
print(f"Ceny po zastosowaniu rabatów:\n{ceny_po_rabacie}")

Ceny po zastosowaniu rabatów:
[[26.991  30.3905 24.6415]
 [44.991  50.3405 40.7915]
 [13.491  15.1905 11.8915]
 [89.991  99.7405 80.7415]]


Zadanie 1c: Oblicz koszt zakupu każdego produktu. Każdy produkt ma inną
marżę: A=30%, B=40%, C=25%, D=50%.


In [5]:
marza = np.array([[0.30], [0.40], [0.25], [0.50]])
ceny_z_marza = ceny * (1 + marza)
print(f"Ceny po dodaniu marży:\n{ceny_z_marza}")

Ceny po dodaniu marży:
[[ 38.987   41.587   37.687 ]
 [ 69.986   74.186   67.186 ]
 [ 18.7375  19.9875  17.4875]
 [149.985  157.485  142.485 ]]


Zadanie 1d: Wyświetl najtańszy sklep dla każdego produktu


Ćwiczenie 2: Reshape i łączenie danych (20 min)
Cel
Zmień kształt danych i połącz tablice z różnych źródeł.

Zadanie 2a — Reshape

In [6]:
# Dane miesięczne z jednego roku (flat)
dane_flat = np.array([120, 135, 98, 142, 167, 189, 201, 178, 156, 143, 198, 221])
# Przekształć na kwartały (4 kwartały × 3 miesiące)
kwartaly = dane_flat.reshape(4, 3)
print(f"Kwartały:\n{kwartaly}")
print(f"Suma per kwartał: {kwartaly.sum(axis=1)}")
print(f"Najlepszy kwartał: Q{kwartaly.sum(axis=1).argmax() + 1}")

Kwartały:
[[120 135  98]
 [142 167 189]
 [201 178 156]
 [143 198 221]]
Suma per kwartał: [353 498 535 562]
Najlepszy kwartał: Q4


Zadanie 2b — Stacking


In [7]:
# Dane z 3 oddziałów (osobne tablice)
warszawa = np.array([150, 160, 170, 180])
krakow = np.array([120, 130, 140, 150])
wroclaw = np.array([90, 100, 110, 120])
# Połącz w macierz (3 oddziały × 4 kwartały)
wszystkie = np.vstack([warszawa, krakow, wroclaw])
print(f"Wszystkie:\n{wszystkie}")
print(f"Suma per oddział: {wszystkie.sum(axis=1)}")
print(f"Suma per kwartał: {wszystkie.sum(axis=0)}")

Wszystkie:
[[150 160 170 180]
 [120 130 140 150]
 [ 90 100 110 120]]
Suma per oddział: [660 540 420]
Suma per kwartał: [360 390 420 450]


Zadanie 2c — Praktyczne (samodzielnie)


In [8]:
sprzedaz_flat = np.array([100, 200, 150, 300, 250, 180, 120, 220, 170, 310, 260, 190])
sprzedaz_miesiace = sprzedaz_flat.reshape(6, 2)
srednia_produkt = sprzedaz_miesiace.mean(axis=1)
print(f"Średnia sprzedaż na produkt:\n{srednia_produkt}")
roznica = sprzedaz_miesiace[:, 1] - sprzedaz_miesiace[:, 0]
print(f"Różnica między miesiącami:\n{roznica}")

Średnia sprzedaż na produkt:
[150. 225. 215. 170. 240. 225.]
Różnica między miesiącami:
[100 150 -70 100 140 -70]


Zadanie 2d — Flatten i concatenate

In [9]:
wektor_flat = kwartaly.flatten()
print(f"Wektor:\n{wektor_flat}")
wektor_powiekszony = np.concatenate([wektor_flat, np.array([235])])
print(f"Wektor powiększony:\n{wektor_powiekszony}")

Wektor:
[120 135  98 142 167 189 201 178 156 143 198 221]
Wektor powiększony:
[120 135  98 142 167 189 201 178 156 143 198 221 235]


Ćwiczenie 3: Analiza danych finansowych (30 min)
Cel
Samodzielna analiza danych finansowych firmy z użyciem zaawansowanych operacji NumPy


In [10]:
np.random.seed(2026)
# 8 pracowników, dane roczne
pracownicy = ['Anna', 'Jan', 'Ewa', 'Marek', 'Kasia', 'Piotr', 'Zofia', 'Tomek']
pensje = np.array([5500, 7200, 4800, 9100, 6300, 4200, 8500, 5800])
staz = np.array([3, 8, 2, 15, 5, 1, 12, 4])
oceny = np.array([4.2, 3.8, 4.5, 4.0, 4.7, 3.5, 4.3, 3.9])
# Sprzedaż miesięczna 4 produktów przez 6 miesięcy
produkty_nazwy = ['Laptop', 'Tablet', 'Smartfon', 'Akcesorium']
sprzedaz = np.random.randint(20, 200, size=(4, 6))
ceny_produktow = np.array([3500, 1800, 2500, 150])

Zadanie 3a: Analiza wynagrodzeń

In [11]:
srednia= pensje.mean()
print(f"Średnia pensja: {srednia:.2f} PLN")
mediana = np.median(pensje)
print(f"Mediana pensji: {mediana:.2f} PLN")
odchylenie = pensje.std()
print(f"Odchylenie standardowe: {odchylenie:.2f} PLN")
powyzej_sredniej = pensje > srednia
print(f"Pracownicy z pensją powyżej średniej:\n{np.array(pracownicy)[powyzej_sredniej]}")
ponizej_mediany = pensje < mediana
print(f"Pracownicy z pensją poniżej mediany:\n{np.array(pracownicy)[ponizej_mediany]}")
rozstep = pensje.max() - pensje.min()
print(f"Rozstęp pensji: {rozstep:.2f} PLN")
iqr = np.percentile(pensje, 75) - np.percentile(pensje, 25)
print(f"IQR pensji: {iqr:.2f} PLN")

Średnia pensja: 6425.00 PLN
Mediana pensji: 6050.00 PLN
Odchylenie standardowe: 1616.90 PLN
Pracownicy z pensją powyżej średniej:
['Jan' 'Marek' 'Zofia']
Pracownicy z pensją poniżej mediany:
['Anna' 'Ewa' 'Piotr' 'Tomek']
Rozstęp pensji: 4900.00 PLN
IQR pensji: 2200.00 PLN


Zadanie 3b: System premii (np.where)

In [12]:
premia=np.where(oceny >= 4.5, 2000, np.where(oceny >= 4.0, 1000, 0))
nowe_wynagrodzenie=pensje + premia
print(f"Nowe wynagrodzenia po premii:\n{nowe_wynagrodzenie}")
max_podwyzka = premia.argmax()
print(f"Największą podwyżkę otrzyma: {pracownicy[max_podwyzka]} ({premia[max_podwyzka]} PLN)")

Nowe wynagrodzenia po premii:
[ 6500  7200  6800 10100  8300  4200  9500  5800]
Największą podwyżkę otrzyma: Ewa (2000 PLN)


Zadanie 3c: Ranking (argsort)

In [13]:
sortowanie_po_pensji = np.argsort(pensje)[::-1]
print(f"Pracownicy posortowani według pensji:\n{np.array(pracownicy)[sortowanie_po_pensji]}")

Pracownicy posortowani według pensji:
['Marek' 'Zofia' 'Jan' 'Kasia' 'Tomek' 'Anna' 'Ewa' 'Piotr']


Zadanie 3d: Korelacja

In [14]:
np.corrcoef(staz, pensje)[0, 1]   
print(f"Korelacja między stażem a pensją: {np.corrcoef(staz, pensje)[0, 1]:.2f}")

print(f"Korelacja między ocenami a pensją: {np.corrcoef(oceny, pensje)[0, 1]:.2f}")
#Która korelacja jest silniejsza?(wyższa bezwzględna wartość)
if abs(np.corrcoef(staz, pensje)[0, 1]) > abs(np.corrcoef(oceny, pensje)[0, 1]):
    print("Silniejsza korelacja jest między stażem a pensją.")
else:
    print("Silniejsza korelacja jest między ocenami a pensją.")

Korelacja między stażem a pensją: 0.99
Korelacja między ocenami a pensją: 0.12
Silniejsza korelacja jest między stażem a pensją.


Zadanie 3e: Analiza sprzedaży (broadcasting)



In [15]:
ceny_kol = ceny_produktow.reshape(4, 1) 
przychod = sprzedaz * ceny_kol
# Który produkt przyniósł największy łączny przychód? (axis=1, argmax)
print(f"Łączny przychód per produkt:\n{przychod.sum(axis=1)}")
# Który miesiąc był najlepszy łącznie? (axis=0, argmax)
print(f"Najlepszy miesiąc: {przychod.sum(axis=0).argmax() + 1}")
# Trend: porównaj pierwsze 3 miesiące vs ostatnie 3
print(f"Łączny przychód z pierwszych 3 miesięcy: {przychod[:, :3].sum()}")
# Podpowiedź: przychod[:, :3].sum() vs przychod[:, 3:].sum()
print(f"Łączny przychód z ostatnich 3 miesięcy: {przychod[:, 3:].sum()}")



Łączny przychód per produkt:
[1624000 1360800 1945000   70650]
Najlepszy miesiąc: 2
Łączny przychód z pierwszych 3 miesięcy: 2463950
Łączny przychód z ostatnich 3 miesięcy: 2536500


Ćwiczenie 4: Generowanie danych (15 min)
Cel
Wygeneruj realistyczne dane biznesowe i przeanalizuj je.

In [16]:

np.random.seed(42)
# Wygeneruj dane o 100 klientach sklepu:
# - wiek: rozkład normalny, średnia 35, std 10, zaokrąglony do int, min 18
# - wydatki_miesiecznie: rozkład normalny, średnia 500, std 200, min 0
# - liczba_wizyt: rozkład Poissona, lambda=5
# Podpowiedź: np.clip() ogranicza wartości do zakresu
wiek = np.clip(np.random.normal(35, 10, 100).astype(int), 18, None)
wydatki = np.clip(np.random.normal(500, 200, 100), 0, None)
wizyty = np.random.poisson(5, 100)


Krok 2 — Analiza (samodzielnie)


In [23]:
# 1. Statystyki opisowe każdej zmiennej (mean, median, std, min, max)
print(f"Wiek — średnia: {wiek.mean():.1f}, mediana: {np.median(wiek):.1f}")
# 2. Korelacja wiek vs wydatki
print(f"Korelacja wiek vs wydatki: {np.corrcoef(wiek, wydatki)[0, 1]:.2f}")
# 3. Korelacja wizyty vs 
print(f'Korelacja wizyty vs wydatki: {np.corrcoef(wizyty, wydatki)[0, 1]:.2f}')
# 4. Segmentacja klientów za pomocą np.where:
# - "WYSOKI" gdy wydatki > średnia + std
# - "NISKI" gdy wydatki < średnia - std
# - "ŚREDNI" w pozostałych przypadkach
# Podpowiedź: zagnieżdżony np.where (jak w zadaniu 3b)
sr = wydatki.mean()
sd = wydatki.std()
segment =  np.where(wydatki > sr + sd, 'WYSOKI', np.where(wydatki < sr - sd, 'NISKI', 'ŚREDNI'))
# 5. Ile klientów w każdym segmencie? Użyj np.unique(..., return_counts=True)
unikat, counts = np.unique(segment, return_counts=True)
print(f"Segementy klientów:\n{dict(zip(unikat, counts))}")

Wiek — średnia: 33.6, mediana: 33.0
Korelacja wiek vs wydatki: -0.12
Korelacja wizyty vs wydatki: -0.16
Segementy klientów:
{np.str_('NISKI'): np.int64(17), np.str_('WYSOKI'): np.int64(12), np.str_('ŚREDNI'): np.int64(71)}
